update
Signed-off-by: Conke Hu <conke.hu@maxwit.com>

diff --git a/service/hadoop b/service/hadoop
--- a/service/hadoop
+++ b/service/hadoop
@@ -2,13 +2,22 @@ cmd=$1
 
 case $cmd in
 start)
-	$HADOOP_HOME/sbin/start-dfs.sh || return 1
-	$HADOOP_HOME/sbin/start-yarn.sh || return 1
-	$HADOOP_HOME/sbin/mr-jobhistory-daemon.sh start historyserver || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/sbin/start-dfs.sh || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/sbin/start-yarn.sh || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh start historyserver || return 1
 	;;
 stop)
-	$HADOOP_HOME/sbin/mr-jobhistory-daemon.sh stop historyserver || return 1
-	$HADOOP_HOME/sbin/stop-dfs.sh || return 1
-	$HADOOP_HOME/sbin/stop-yarn.sh || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh stop historyserver || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/sbin/stop-dfs.sh || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/sbin/stop-yarn.sh || return 1
+	;;
+init)
+	sudo -u $hadoop_user $HADOOP_HOME/bin/hadoop fs -mkdir -p /tmp /user || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/bin/hadoop fs -chmod g+w /tmp /user || return 1
+	sudo -u $hadoop_user $HADOOP_HOME/bin/hadoop fs -ls / || return 1
+	;;
+*)
+	echo "invalid cmd '$1'"
+	exit 1
 	;;
 esac
